FROM python:3.11-slim
WORKDIR /app
COPY ./back_end/back_end/celery_service /app/
RUN pip install --no-cache-dir -r requirements.txt
CMD ["celery", "-A", "celery_config.celery_app", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
