FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
    bluez \
    dbus \
    python3-pip
WORKDIR /app
COPY ./hub/hub /app
RUN pip install --no-cache-dir -r requirements.txt
CMD [ "python", "main.py" ]